### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by bmeynell** [studio24/wordpress-multi-env-config#4]
May we have one?

**Comment by simonrjones** [comment]
hi there

Am happy to add this, however due to how WP is organised this code needs to currently be in the WP root folder. So I'm not sure how much benefit there is in installing this via Composer since there is no library style files that can be used? 

If you have any ideas or pointers on how to use Composer in this instance please do share. 

best wishes,
Simon

**Comment by simonrjones** [comment]
adding some links to WordPress & Composer usage for investigation

http://wptavern.com/a-narrative-of-using-composer-in-a-wordpress-plugin
https://deliciousbrains.com/using-composer-manage-wordpress-themes-plugins/
https://roots.io/using-composer-with-wordpress/

**Comment by simonrjones** [comment]
Closing this at present since it's not clear how to use composer to help manage this. Obv if anyone has any ideas please feel free to post!
