### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by MarcoWilli** [studio24/wordpress-multi-env-config#7]
Hi!
I found this via a T3N-article and tried to use it now.
Got problem "Error establishing a database connection" on local dev machine and on live system though DB-settings are correct.
Can´t find the error...

EDIT: It´s a multisite installation but I don´t think it matters?!

**Comment by aplanting** [comment]
this issue can be resolved by switching the env with the default in the abspath.

the database settings need to be loaded before the rest. In the code below rules are switched.

// Load config file for current environment
include ABSPATH . '/wp-config.' . WP_ENV . '.php';

// Load default config
include ABSPATH . '/wp-config.default.php';

**Comment by simonrjones** [comment]
Sorry I've not replied earlier to this. 

The general intention is to load default config settings first, then override with your environment settings. However, since WordPress mostly uses PHP constants to set config settings, you can't override them anyway so this is a bit of a moot point.

Are you able to share your _wp-config.default.php_ file since I cannot see why this would need to be loaded after DB details are set in your local environment file (please remove any sensitive data). From my understanding only settings (e.g. constants) are set, there isn't any functional code running in these config files.

**Comment by simonrjones** [comment]
closing due to no follow up comment
